### ISSUE TITLE
generate task failing on gradle 8.0

### ISSUE THREAD

**Issue by mohitchauhan** [infinum/android-collar#63]
## Stacktrace

Caused by: java.lang.NullPointerException: null cannot be cast to non-null type com.infinum.collar.plugin.CollarExtension
        at com.infinum.collar.plugin.tasks.GenerateTask.doOnRun(GenerateTask.kt:50)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.7 (Eclipse Adoptium 17.0.7+7)
OS:           Mac OS X 10.15.7 x86_64

**Comment by bojankoma** [comment]
Hi @mohitchauhan thank you for the report.
I'm having a hard time reproducing this issue, what version of Collar are you using?

**Comment by mohitchauhan** [comment]
Hi @bojankoma unable to reproduce this issue So closing it. Thanks a lot for this nice library
